# NumPy Lecture Questions

### Q1.1 Create a 2 by 2 array, use different ways 
#### Q1.1a
```Python 
d2array_a = 
print ('a:\n',d2array_a)```
#### Q1.1b
```Python 
from_list = 
d2array_b = 
print('b:\n',d2array_b)
```
#### Q1.1c
```Python 
d2array_c = 
print('c:\n',d2array_c)```

#### Q1.1d For each statement in a, b, and c, specify the data types:
```Python 
d2array_a = 
d2array_b = 
d2array_c = ```

In [1]:
import numpy as np

In [5]:
np.random.rand(2,2)

array([[0.02116062, 0.25231172],
       [0.94131624, 0.70306002]])

In [29]:
# In class exercise for student to fill in 

# create a 2 by 2 array, use different ways 
# option a
d2array_a = np.random.rand(2,2)
print ('a:\n',d2array_a)

a:
 [[0.42116192 0.60931418]
 [0.78843335 0.22990076]]


In [30]:
# option b
from_list = [[2,3],[9,8]]
d2array_b = np.array(from_list)
print('b:\n',d2array_b)

b:
 [[2 3]
 [9 8]]


In [31]:
# option c
grid = [[1,2]]
d2array_c = np.concatenate([grid,grid]) 
print('c:\n',d2array_c)

c:
 [[1 2]
 [1 2]]


In [17]:
# specify the data type
d2array_c = d2array_c.dtype
d2array_a = d2array_a.dtype
d2array_b = d2array_b.dtype


In [32]:
print(f'Data type for a: {d2array_a.dtype}')
print(f'Data type for b: {d2array_b.dtype}')
print(f'Data type for c: {d2array_c.dtype}')

Data type for a: float64
Data type for b: int32
Data type for c: int32


In [33]:
type(d2array_b[0][1])

numpy.int32

#### Q2. Define the dt object again, use `str` instead of `unicode_` for course, and `int` for points
```Python
dt = np.dtype([('course', ????, 16), ('points', ?????, (2,))])
grades = np.array([('bio', (18.0, 67.0)), ('math', (87.0, 47.0))], dtype=dt)
```

In [ ]:
# In class exercise for student to fill in 

# write the dt again, use str instead of unicode_ for course, and int for points
dt = np.dtype([('course',''' ''', 16), ('points',''' ''', (2,))])
grades = np.array([('bio', (18.0, 67.0)), ('math', (87.0, 47.0))], dtype=dt)

#### Q3. What is the type of 'bio'
```Python
print ('\nvalue:',?????,', type:',type(?????))
```

In [ ]:
# what is the type of 'bio'
print ('\nvalue:',''' ''',', type:',''' ''',)

#### Q4. What is the type of points?
```Python
print ('\nvalue:',?????,', type:',type(?????))
```

In [ ]:
# what is the type of points
print ('\nvalue:',''' ''',', type:',''' ''')

#### Q5. What are the bio class points? **1
```Python
print ('\nvalue:',?????,', points I got:',?????)
```

In [ ]:
# what are the bio class points 
print ('\nvalue:',', points I got:')

#### Q6. What are the math class points ? **2
```Python
print ('\nvalue:',?????,', points I got:',?????)
```

In [ ]:
# what are the math class points 
print ('\nvalue:',', points I got:')

#### Q7. What are the data types of **1 and **2?

In [ ]:
# what is the type of grades[0]['course']
print ('\nvalue:',', type:')

In [ ]:
# what is the type of grades[1]['points']
print ('\nvalue:',', type:')

----------------------------------------------------------
### Universal functions
----
#### Q8. Find the square root of array a using the numpy lib functions


In [ ]:
# find the square root of array a using the numpy lib functions


#### Q9. Find the exponents of array b using the numpy lib functions


In [ ]:
# find the exponents of array b using the numpy lib functions


#### Q10. Given: 
```Python
a = np.arange(12).reshape(3,4)
```
#### Q10A. Find the sum of each column
```Python
a.sum(????)
```

In [ ]:
# In class exercise for student to enter
a = np.arange(12).reshape(3,4)
print (a)

#### Q10B. Find the min of each row
```Python
a.min(????)
```

In [ ]:
print ('min of each row:', a.sum())

----------------------------------------------------------
### Slicing
#### Q11. Find the following slices of the array:

#### Q11A. Each row in the second column of a, there are multiple ways!
```Python
print (a[])
print (a[])
```

In [ ]:
# In class exercise for student to enter
# find the following slices of the array:

# each row in the second column of a
print (a[])
print (a[])


#### Q11B. Each column in the second and the third rows
```Python
print (a[])
```

In [ ]:
# each column in the second and the third rows
print (a[])

### Fancy Slicing
#### Q12. Given:
```Python
a = array([[33,  3, 43, 68, 97],
       [42, 33, 82, 25, 82],
       [57, 27, 15, 13, 78],
       [11, 29, 13, 28, 98],
       [92, 20, 78, 73, 57],
       [ 7, 48,  2,  4, 81],
       [15, 63, 50,  3, 37],
       [25, 29, 63, 76, 38],
       [37, 10, 84, 56,  4],
       [63,  1, 73, 28, 95]])
```
#### can you write code to get:
```Python
array([2],
      [15],
      [63])
```

In [ ]:
# In class exercise for student to enter
# given array a:
a = np.array([[33,  3, 43, 68, 97],
       [42, 33, 82, 25, 82],
       [57, 27, 15, 13, 78],
       [11, 29, 13, 28, 98],
       [92, 20, 78, 73, 57],
       [ 7, 48,  2,  4, 81],
       [15, 63, 50,  3, 37],
       [25, 29, 63, 76, 38],
       [37, 10, 84, 56,  4],
       [63,  1, 73, 28, 95]])
# fancy slice the array to find the array([2],[15],[63]):


**End of Module**